(function (global) {
  const keywordMap = {
    city: ["城市", "夜景", "地铁", "街", "霓虹", "下班", "通勤", "便利店", "独处"],
    travel: ["旅行", "海边", "火车", "车窗", "露营", "公路", "路线", "风景"],
    food: ["美食", "探店", "咖啡", "甜品", "餐厅", "吃", "上菜"],
    graduation: ["毕业", "青春", "朋友", "回忆", "离别", "校园", "照片"],
    fitness: ["健身", "训练", "力量", "跳绳", "运动", "卡点", "动作"],
    lonely: ["孤独", "独白", "一个人", "冷感", "克制", "失落"],
    warm: ["温暖", "治愈", "生活感", "柔和", "轻松"],
    sad: ["悲伤", "想哭", "遗憾", "失恋", "离别", "emo"],
    premium: ["高级", "质感", "电影感", "精致", "氛围"],
    energetic: ["高能", "燃", "抓人", "冲击", "快", "热血"],
    beat: ["卡点", "节奏", "转场", "鼓点", "快切", "律动"],
    soft: ["不要太吵", "不抢", "旁白", "口播", "安静", "轻", "人声少"]
  };

  const labelMap = {
    city: "城市",
    travel: "旅行",
    food: "美食",
    graduation: "毕业",
    fitness: "健身",
    lonely: "孤独",
    warm: "温暖",
    sad: "悲伤",
    premium: "高级",
    energetic: "高能",
    beat: "卡点",
    soft: "不抢人声",
    calm: "平静",
    nostalgic: "回忆",
    happy: "明亮",
    clean: "干净",
    focused: "专注",
    bold: "强势",
    playful: "轻快",
    free: "开阔"
  };

  const catalog = [
    {
      id: "trk-001",
      title: "Neon After Work",
      artist: "North Bridge Lab",
      bpm: 92,
      energy: 42,
      moods: ["lonely", "premium", "calm"],
      genres: ["lofi", "ambient", "citypop"],
      scenes: ["city", "night", "work"],
      platforms: ["SoundCloud", "Artlist", "网易云示例歌单"],
      heat: 83,
      vocal: "instrumental",
      structure: "0:00 氛围铺底，0:24 鼓组进入，0:58 合成器副旋律",
      download: "免版税素材库 / 创作者订阅库",
      hook: "孤独感足，鼓点克制，适合夜景转场和独白留白。"
    },
    {
      id: "trk-002",
      title: "Glass Metro Line",
      artist: "Signal Room",
      bpm: 104,
      energy: 58,
      moods: ["premium", "focused", "lonely"],
      genres: ["electronica", "minimal", "downtempo"],
      scenes: ["city", "travel", "night"],
      platforms: ["Epidemic Sound", "QQ 音乐示例歌单", "Bandcamp"],
      heat: 78,
      vocal: "vocal-chop",
      structure: "0:00 冷感铺垫，0:17 切分节奏，0:45 低频增强",
      download: "商用音乐平台 / 独立音乐人页面",
      hook: "节奏更清晰，适合地铁、楼梯、街灯等画面卡点。"
    },
    {
      id: "trk-003",
      title: "Last Train Window",
      artist: "Mira Lo",
      bpm: 76,
      energy: 30,
      moods: ["sad", "lonely", "warm"],
      genres: ["piano", "ambient", "cinematic"],
      scenes: ["city", "graduation", "memory"],
      platforms: ["Artlist", "Apple Music 示例歌单", "网易云示例歌单"],
      heat: 70,
      vocal: "instrumental",
      structure: "0:00 钢琴主题，0:36 弦乐垫底，1:12 情绪抬升",
      download: "影视配乐库 / 版权音乐平台",
      hook: "悲伤但不压抑，适合独白、夜景慢镜和回忆片段。"
    },
    {
      id: "trk-004",
      title: "Polaroid Summer",
      artist: "June Archive",
      bpm: 116,
      energy: 64,
      moods: ["warm", "happy", "nostalgic"],
      genres: ["indie-pop", "folk", "acoustic"],
      scenes: ["travel", "graduation", "food"],
      platforms: ["Epidemic Sound", "小红书示例热榜", "Spotify 示例歌单"],
      heat: 91,
      vocal: "light-vocal",
      structure: "0:00 吉他开场，0:15 鼓掌节拍，0:48 副歌抬升",
      download: "创作者音乐库 / 平台热榜授权入口",
      hook: "青春感强，旋律记忆点明显，适合旅行和朋友群像。"
    },
    {
      id: "trk-005",
      title: "Ticket To Morning",
      artist: "Field Notes",
      bpm: 98,
      energy: 48,
      moods: ["warm", "nostalgic", "calm"],
      genres: ["folk", "lofi", "acoustic"],
      scenes: ["travel", "graduation", "food"],
      platforms: ["Artlist", "网易云示例歌单", "YouTube Audio Library"],
      heat: 76,
      vocal: "instrumental",
      structure: "0:00 木吉他主题，0:28 轻鼓进入，1:05 口琴点缀",
      download: "免版税音乐库 / 视频平台音乐库",
      hook: "温暖、不抢画面，适合叙事型 vlog 和长镜头。"
    },
    {
      id: "trk-006",
      title: "Friends On Platform 3",
      artist: "Blue Lunch Club",
      bpm: 124,
      energy: 72,
      moods: ["happy", "warm", "energetic"],
      genres: ["indie-pop", "dance-pop", "band"],
      scenes: ["graduation", "travel"],
      platforms: ["QQ 音乐示例歌单", "Spotify 示例歌单", "Epidemic Sound"],
      heat: 88,
      vocal: "light-vocal",
      structure: "0:00 人声切片，0:12 鼓组进，0:38 副歌爆发",
      download: "流媒体平台 / 商用翻牌授权库",
      hook: "更明亮，适合毕业旅行的合照、奔跑和高光片段。"
    },
    {
      id: "trk-007",
      title: "Rep Counter",
      artist: "Frame Lock",
      bpm: 142,
      energy: 88,
      moods: ["energetic", "focused", "bold"],
      genres: ["trap", "electronic", "sport"],
      scenes: ["fitness", "street"],
      platforms: ["抖音示例热榜", "Epidemic Sound", "SoundCloud"],
      heat: 86,
      vocal: "vocal-chop",
      structure: "0:00 低频冲击，0:08 Drop，0:32 第二段卡点",
      download: "短视频音乐库 / 商用运动曲库",
      hook: "强鼓点和短周期 Drop，适合动作剪辑与快速转场。"
    },
    {
      id: "trk-008",
      title: "Fast Cut Routine",
      artist: "Beat Foundry",
      bpm: 128,
      energy: 80,
      moods: ["energetic", "clean", "confident"],
      genres: ["house", "electronic", "fitness"],
      scenes: ["fitness", "city"],
      platforms: ["Artlist", "抖音示例热榜", "BeatStars"],
      heat: 79,
      vocal: "instrumental",
      structure: "0:00 四拍建立，0:16 主节奏，0:48 Break 后回落",
      download: "节拍平台 / 免版税曲库",
      hook: "BPM 稳定，剪辑点清楚，适合卡动作和字幕节奏。"
    },
    {
      id: "trk-009",
      title: "Cafe Table Light",
      artist: "Soft Manual",
      bpm: 88,
      energy: 36,
      moods: ["warm", "calm", "clean"],
      genres: ["jazz-hop", "lofi", "acoustic"],
      scenes: ["food", "city", "daily"],
      platforms: ["小红书示例歌单", "网易云示例歌单", "YouTube Audio Library"],
      heat: 84,
      vocal: "instrumental",
      structure: "0:00 电钢琴，0:20 轻鼓点，0:52 贝斯小走句",
      download: "视频平台音乐库 / 轻音乐素材库",
      hook: "轻松生活感强，不会抢口播，适合探店和日常记录。"
    },
    {
      id: "trk-010",
      title: "Butter Window",
      artist: "Sunday Index",
      bpm: 102,
      energy: 50,
      moods: ["happy", "warm", "playful"],
      genres: ["bossa", "jazz", "pop"],
      scenes: ["food", "travel", "daily"],
      platforms: ["Epidemic Sound", "小红书示例热榜", "Spotify 示例歌单"],
      heat: 82,
      vocal: "instrumental",
      structure: "0:00 吉他律动，0:18 打击乐，0:44 旋律变化",
      download: "创作者订阅库 / 商用音乐平台",
      hook: "有精致餐厅感，适合甜品、咖啡和慢节奏探店。"
    },
    {
      id: "trk-011",
      title: "Quiet Checklist",
      artist: "Paper Plan Studio",
      bpm: 84,
      energy: 28,
      moods: ["calm", "clean", "focused"],
      genres: ["minimal", "lofi", "ambient"],
      scenes: ["daily", "work", "food"],
      platforms: ["YouTube Audio Library", "Artlist", "B 站示例素材库"],
      heat: 68,
      vocal: "instrumental",
      structure: "0:00 空间底噪，0:22 极简鼓点，1:00 低音变化",
      download: "免版税音乐库 / 平台素材库",
      hook: "最不抢人声，适合教程、旁白和工作流 vlog。"
    },
    {
      id: "trk-012",
      title: "Rain In Semester",
      artist: "Low Battery Club",
      bpm: 72,
      energy: 34,
      moods: ["sad", "nostalgic", "warm"],
      genres: ["piano", "lofi", "cinematic"],
      scenes: ["graduation", "memory", "travel"],
      platforms: ["网易云示例歌单", "Artlist", "Apple Music 示例歌单"],
      heat: 73,
      vocal: "instrumental",
      structure: "0:00 雨声与钢琴，0:30 鼓点轻入，1:10 弦乐抬升",
      download: "影视配乐库 / 独立音乐授权页",
      hook: "回忆感强，适合毕业、离别、旧照片和慢镜头。"
    },
    {
      id: "trk-013",
      title: "Coastline Receipt",
      artist: "Map Folder",
      bpm: 108,
      energy: 60,
      moods: ["warm", "free", "nostalgic"],
      genres: ["indie", "acoustic", "pop"],
      scenes: ["travel", "food", "graduation"],
      platforms: ["Spotify 示例歌单", "Epidemic Sound", "小红书示例歌单"],
      heat: 80,
      vocal: "light-vocal",
      structure: "0:00 海浪采样，0:14 吉他进，0:42 副歌铺开",
      download: "创作者曲库 / 流媒体授权入口",
      hook: "旅行感明确，适合海边、车窗、路牌和开阔画面。"
    },
    {
      id: "trk-014",
      title: "Midnight Receipt",
      artist: "K Line",
      bpm: 118,
      energy: 69,
      moods: ["premium", "bold", "city"],
      genres: ["synthwave", "electronic", "citypop"],
      scenes: ["city", "night", "fitness"],
      platforms: ["SoundCloud", "QQ 音乐示例歌单", "BeatStars"],
      heat: 75,
      vocal: "instrumental",
      structure: "0:00 合成器琶音，0:16 鼓组推进，0:50 低频增强",
      download: "独立音乐平台 / 商用节拍平台",
      hook: "更有速度和霓虹感，适合夜景快切但可能略抢画面。"
    },
    {
      id: "trk-015",
      title: "Small Room Sunrise",
      artist: "Mellow Desk",
      bpm: 82,
      energy: 32,
      moods: ["warm", "calm", "lonely"],
      genres: ["ambient", "lofi", "piano"],
      scenes: ["daily", "city", "work"],
      platforms: ["B 站示例素材库", "Artlist", "YouTube Audio Library"],
      heat: 67,
      vocal: "instrumental",
      structure: "0:00 Pad 铺底，0:26 钢琴进入，1:06 柔和展开",
      download: "平台素材库 / 免版税配乐库",
      hook: "安静克制，适合独白、早晨工作和低饱和生活片段。"
    },
    {
      id: "trk-016",
      title: "Quick Bite Montage",
      artist: "Snack Sync",
      bpm: 120,
      energy: 62,
      moods: ["happy", "playful", "clean"],
      genres: ["funk", "pop", "jazz-hop"],
      scenes: ["food", "daily"],
      platforms: ["小红书示例热榜", "Epidemic Sound", "抖音示例热榜"],
      heat: 89,
      vocal: "instrumental",
      structure: "0:00 Bass riff，0:10 拍手节奏，0:35 小 Drop",
      download: "短视频音乐库 / 创作者订阅库",
      hook: "轻快、卡点友好，适合美食制作、上菜和口播间隔。"
    }
  ];

  global.AppData = {
    keywordMap,
    labelMap,
    catalog
  };
})(window);
